"""initial_migration

Revision ID: 1645cce915fe
Revises: f839e9625128
Create Date: 2022-08-22 16:03:26.391353

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1645cce915fe'
down_revision = 'f839e9625128'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sat_jobs', sa.Column('Conflicts', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sat_jobs', 'Conflicts')
    # ### end Alembic commands ###
