"""initial_migration

Revision ID: 2effdda461f6
Revises: 
Create Date: 2022-06-28 13:52:26.866433

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2effdda461f6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sat_jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('unit_prop_vals', sa.Float(), nullable=True),
    sa.Column('decision_vars', sa.Float(), nullable=True),
    sa.Column('time', sa.Float(), nullable=True),
    sa.Column('algorithm', sa.String(length=32), nullable=True),
    sa.Column('benchmark', sa.String(length=32), nullable=True),
    sa.Column('log_file', sa.String(length=128), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sat_jobs')
    # ### end Alembic commands ###
