"""initial_migration

Revision ID: 40cfcda4c486
Revises: 
Create Date: 2022-06-28 15:52:08.130755

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '40cfcda4c486'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sat_jobs',
    sa.Column('ID', sa.Integer(), nullable=False),
    sa.Column('Unit Propagations', sa.Float(), nullable=True),
    sa.Column('Derivations of Decision Variables', sa.Float(), nullable=True),
    sa.Column('Time of Execution', sa.Float(), nullable=True),
    sa.Column('Algorithm', sa.String(length=32), nullable=True),
    sa.Column('Benchmark', sa.String(length=32), nullable=True),
    sa.Column('Log File', sa.String(length=128), nullable=True),
    sa.Column('Date of Run', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('ID')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sat_jobs')
    # ### end Alembic commands ###
