"""initial_migration

Revision ID: 50b26edcf335
Revises: 89ad319e489f
Create Date: 2022-09-02 19:29:33.407157

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '50b26edcf335'
down_revision = '89ad319e489f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sat_nqueens',
    sa.Column('ID', sa.Integer(), nullable=False),
    sa.Column('Unit Propagations', sa.Float(), nullable=True),
    sa.Column('No. Checked UP Clauses', sa.Float(), nullable=True),
    sa.Column('Derivations of Decision Variables', sa.Float(), nullable=True),
    sa.Column('Conflicts', sa.Float(), nullable=True),
    sa.Column('Max Learned Clauses', sa.Float(), nullable=True),
    sa.Column('Time of Execution', sa.Float(), nullable=True),
    sa.Column('Algorithm', sa.String(length=512), nullable=True),
    sa.Column('Number of Queens', sa.String(length=32), nullable=True),
    sa.Column('Log File', sa.String(length=512), nullable=True),
    sa.Column('Date of Run', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('ID')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sat_nqueens')
    # ### end Alembic commands ###
