"""initial_migration

Revision ID: f839e9625128
Revises: 40cfcda4c486
Create Date: 2022-08-07 12:29:18.167958

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f839e9625128'
down_revision = '40cfcda4c486'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sat_jobs', sa.Column('No. Checked UP Clauses', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sat_jobs', 'No. Checked UP Clauses')
    # ### end Alembic commands ###
