version: '3'
services:
  redis:
    image: redis/redis-stack:latest
    container_name: redis-stack-server
    ports:
      - "6379:6379"

  flask-app:
    image: satsolver:latest
    container_name: satsolver
    build:
      context: .
      dockerfile: dockerfiles/dockerfile.main
    restart: always
    environment:
      - FLASK_APP=server:app
      - PORT=8765
      - APP_ENVIRONMENT=PROD
      - REDIS_QUEUE_NAME=satsmt_background_worker_queue
    env_file:
      - dockerfiles/common_vars.env
    ports:
        - '5000:8765'
    depends_on:
      - redis
      - satdb
      - prepare_satdb_on_first_run
    volumes:
      - ./server/:/app/server/
      - satsolver_logs:/app/logs/
  
  redis-worker:
    image: redis-worker:latest
    container_name: redis-worker
    build:
      context: .
      dockerfile: dockerfiles/dockerfile.worker
    environment:
      - REDIS_QUEUE_NAME=satsmt_background_worker_queue
    env_file:
      - dockerfiles/common_vars.env
    volumes:
      - ./satsolver/:/app/satsolver/
      - ./server/:/app/server/
      - satsolver_logs:/app/logs/
    depends_on:
      - redis
  
  prepare_satdb_on_first_run:
    build:
      context: .
      dockerfile: dockerfiles/dockerfile.prepare_db
    environment:
      - FLASK_APP=server:app
      - MIGRATION_NAME=initial_migration
    env_file:
      - dockerfiles/common_vars.env
    depends_on:
      - satdb
    volumes:
      - ./server/:/app/server/

  satdb:
    image: postgres:latest
    container_name: satsolver_db
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=satsolverdb
    ports:
      - 5432:5432
    volumes:
      - satsolver_db_volume:/var/lib/postgresql/data
volumes:
  satsolver_db_volume:
    external: false
  satsolver_logs:
    external: false

