version: '3'
services:
    redis:
        image: redis/redis-stack:latest
        container_name: redis-stack-server
        ports:
          - "6379:6379"

    flask-app:
        image: satsolver:latest
        container_name: satsolver
        build: .
        restart: always
        environment:
          - PORT=8765
          - APP_ENVIRONMENT=PROD
        ports:
            - '5000:8765'
        depends_on:
          - redis