FROM gortibaldik/satsolver_base:0.11 as production
WORKDIR /app
COPY --from=gortibaldik/satsolver_frontend_base:0.1 /app/dist /usr/share/nginx/html
COPY ./server/nginx/default.conf /etc/nginx/conf.d/default.conf
COPY ./satsolver ./satsolver
COPY ./scripts ./scripts
COPY ./server ./server
 
CMD scripts/_docker_main.sh
