FROM gortibaldik/satsolver_base:0.11 as production
WORKDIR /app
COPY ./server ./server
COPY ./satsolver ./satsolver
 
CMD if [ ! -d "server/rq_logs" ]; then mkdir server/rq_logs; fi && \
    rq worker $REDIS_QUEUE_NAME --url redis://redis:6379 > "server/rq_logs/rq_log_file" 2> "server/rq_logs/rq_error_log_file"
