FROM base_image:latest as production
WORKDIR /app
COPY --from=frontend_base_image:latest /app/dist /usr/share/nginx/html
COPY ./server/nginx/default.conf /etc/nginx/conf.d/default.conf
COPY ./satsolver ./satsolver
COPY ./scripts ./scripts
 
CMD scripts/_docker_prepare_db.sh