FROM node:15.7.0-alpine3.10 as build-vue
WORKDIR /app
COPY ./client ./client
 
CMD cd /app/client && \
    echo "starting install" && \
    npm install && \
    echo "starting serve" && \
    npm run serve
