FROM gortibaldik/satsolver_base:0.11 as production
WORKDIR /app
 
CMD if [ ! -d "logs/rq_logs" ]; then mkdir -p logs/rq_logs; fi && \
    rq worker $REDIS_QUEUE_NAME --url redis://redis:6379 > "logs/rq_logs/rq_log_file" 2> "logs/rq_logs/rq_error_log_file"
