FROM gortibaldik/satsolver_base:0.13 as production
WORKDIR /app
COPY ./server/nginx/default.conf.dev /etc/nginx/conf.d/default.conf
COPY ./server/nginx/nginx.conf /etc/nginx/nginx.conf
COPY ./scripts ./scripts
 
CMD scripts/_docker_main_dev.sh
